name: abushakir
version: 1.0.0
homepage: https://github.com/Nabute/Abushakir
description: A Dart/ Flutter Package for Ethiopian calendar system (ባሕረ ሃሳብ). It can help you integrate Ethiopian DateTime, calendar and all the movable fastings with respective holidays.
environment: 
  sdk: '>=2.12.2 <3.0.0'
dependencies: 
  equatable: ^2.0.3
dev_dependencies: 
  test: ^1.14.2
